name: hospital_admin_panel
description: A Flutter web application for hospital administration.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP requests
  http: ^1.2.0

  # State management
  provider: ^6.1.2

  # UI Components
  cupertino_icons: ^1.0.8

  # Charts
  fl_chart: ^0.69.0

  # Date formatting
  intl: ^0.20.2

  # Calendar
  table_calendar: ^3.0.9

  # Socket.IO for real-time updates
  socket_io_client: ^2.0.3+1

  # Video calling with Agora - commented out for web compatibility
  # agora_rtc_engine: ^6.3.2

  # Permissions
  permission_handler: ^12.0.1

  # File picker for reports
  file_picker: ^8.1.2

  # CSV processing
  csv: ^6.0.0

  # Image picker
  image_picker: ^1.0.7

  # UUID generator
  uuid: ^4.2.2

  # Shared preferences
  shared_preferences: ^2.2.3

  # Path provider
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-variant files:
  # - images/a_dot_burr.jpeg:2.0x
  # - images/a_dot_burr.jpeg:3.0x

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
