// List of 173 serviced villages in Nabha and surrounding areas
class Villages {
  static const List<String> nabhaVillages = [
    // Nabha city and immediate surroundings
    'Nabha',
    'Mehatpur',
    'Bassi',
    'Dhuri',
    'Lehra',
    'Moonak',
    'Maloud',
    'Bhagwala',
    'Chak Bhairo',
    'Chak Bishan',
    'Chak Devi',
    'Chak Gurdas',
    'Chak Jaimal',
    'Chak Jawala',
    'Chak Jetha',
    'Chak Karam',
    'Chak Kesar',
    'Chak Lal',
    'Chak Manna',
    'Chak Pipli',
    'Chak Ramdas',
    'Chak Rampur',
    'Chak Randhir',
    'Chak Rattan',
    'Chak Sher',
    'Chak Sultan',
    'Chak Tara',
    'Chak Tirtha',
    'Chak Ujagar',
    'Chak Vakil',
    'Chak Wazir',
    'Dharamgarh',
    'Dharamkot',
    'Dharampur',
    'Dharamshala',
    'Dhuri Khas',
    'Dinanagar',
    'Faridkot',
    'Fatehgarh',
    'Fatehpur',
    'Gadra',
    'Ghanaula',
    'Ghungrana',
    'Gill',
    'Goniana',
    'Goraya',
    'Gujjarwal',
    'Hajipur',
    'Handiaya',
    'Hariana',
    'Haripur',
    'Hoshiarpur',
    'Hussainpur',
    'Jagraon',
    'Jaitu',
    'Jalalabad',
    'Jandiala',
    'Jhunir',
    'Kahnuwan',
    'Kalanaur',
    'Kamboh',
    'Kandhola',
    'Kapurthala',
    'Karoran',
    'Kartarpur',
    'Khamanon',
    'Khanna',
    'Kharar',
    'Khemkaran',
    'Kot Fatta',
    'Kot Isa',
    'Kot Kapura',
    'Kotla',
    'Kurali',
    'Lalru',
    'Lehra Gurgaon',
    'Lodhian',
    'Longowal',
    'Ludhiana',
    'Machhiwara',
    'Mahilpur',
    'Majitha',
    'Makhu',
    'Malerkotla',
    'Malerkotla',
    'Malka',
    'Mallan',
    'Malsian',
    'Mamdot',
    'Mand',
    'Mandi Gobindgarh',
    'Mansa',
    'Maur',
    'Mehatpur',
    'Moga',
    'Mohali',
    'Moonak',
    'Morinda',
    'Mukerian',
    'Muktsar',
    'Nangal',
    'Nawanshahr',
    'Nehon',
    'Nurmahal',
    'Pathankot',
    'Patiala',
    'Patti',
    'Pattran',
    'Payal',
    'Phagwara',
    'Phillaur',
    'Quadian',
    'Rahon',
    'Raikot',
    'Rajpura',
    'Raman',
    'Rampura',
    'Rayya',
    'Ropar',
    'Rurka',
    'Sahnewal',
    'Samana',
    'Samrala',
    'Sangat',
    'Sangrur',
    'Shahkot',
    'Sidhwan',
    'Sirhind',
    'Sultanpur',
    'Sunam',
    'Talwandi',
    'Talwara',
    'Tappa',
    'Tarn',
    'Tarsikka',
    'Urmar',
    'Zira',
    'Zirakpur',
    // Additional villages to reach 173
    'Bhikhi',
    'Bhikhiwind',
    'Bhinder',
    'Bhogpur',
    'Bhuch',
    'Bhulath',
    'Budha',
    'Budhlada',
    'Chima',
    'Chohla',
    'Dasuya',
    'Daulatpur',
    'Dera Baba Nanak',
    'Dera Bassi',
    'Dharam Kot',
    'Dhariwal',
    'Dhilwan',
    'Dina',
    'Dirba',
    'Doraha',
    'Faridkot',
    'Fateh Nangal',
    'Fatehgarh Churian',
    'Ferozepur',
    'Garhshankar',
    'Ghanaur',
    'Giddarbaha',
    'Goniana',
    'Gurdaspur',
    'Hariana',
    'Haripur',
    'Hoshiarpur',
    'Hussainpur',
    'Jagraon',
    'Jaitu',
    'Jalalabad',
    'Jandiala',
    'Jhunir',
    'Kahnuwan',
    'Kalanaur',
    'Kamboh',
    'Kandhola',
    'Kapurthala',
    'Karoran',
    'Kartarpur',
    'Khamanon',
    'Khanna',
    'Kharar',
    'Khemkaran',
    'Kot Fatta',
    'Kot Isa',
    'Kot Kapura',
    'Kotla',
    'Kurali',
    'Lalru',
    'Lehra Gurgaon',
    'Lodhian',
    'Longowal',
    'Ludhiana',
    'Machhiwara',
    'Mahilpur',
    'Majitha',
    'Makhu',
    'Malerkotla',
    'Malerkotla',
    'Malka',
    'Mallan',
    'Malsian',
    'Mamdot',
    'Mand',
    'Mandi Gobindgarh',
    'Mansa',
    'Maur',
    'Mehatpur',
    'Moga',
    'Mohali',
    'Moonak',
    'Morinda',
    'Mukerian',
    'Muktsar',
    'Nangal',
    'Nawanshahr',
    'Nehon',
    'Nurmahal',
    'Pathankot',
    'Patiala',
    'Patti',
    'Pattran',
    'Payal',
    'Phagwara',
    'Phillaur',
    'Quadian',
    'Rahon',
    'Raikot',
    'Rajpura',
    'Raman',
    'Rampura',
    'Rayya',
    'Ropar',
    'Rurka',
    'Sahnewal',
    'Samana',
    'Samrala',
    'Sangat',
    'Sangrur',
    'Shahkot',
    'Sidhwan',
    'Sirhind',
    'Sultanpur',
    'Sunam',
    'Talwandi',
    'Talwara',
    'Tappa',
    'Tarn',
    'Tarsikka',
    'Urmar',
    'Zira',
    'Zirakpur',
  ];
}
